package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiIdempotencyKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIdempotencyKeyAllPropertiesEquals(ApiIdempotencyKey expected, ApiIdempotencyKey actual) {
        assertApiIdempotencyKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertApiIdempotencyKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIdempotencyKeyAllUpdatablePropertiesEquals(ApiIdempotencyKey expected, ApiIdempotencyKey actual) {
        assertApiIdempotencyKeyUpdatableFieldsEquals(expected, actual);
        assertApiIdempotencyKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIdempotencyKeyAutoGeneratedPropertiesEquals(ApiIdempotencyKey expected, ApiIdempotencyKey actual) {
        assertThat(actual)
            .as("Verify ApiIdempotencyKey auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIdempotencyKeyUpdatableFieldsEquals(ApiIdempotencyKey expected, ApiIdempotencyKey actual) {
        assertThat(actual)
            .as("Verify ApiIdempotencyKey relevant properties")
            .satisfies(a -> assertThat(a.getIdemKey()).as("check idemKey").isEqualTo(expected.getIdemKey()))
            .satisfies(a -> assertThat(a.getRequestHash()).as("check requestHash").isEqualTo(expected.getRequestHash()))
            .satisfies(a -> assertThat(a.getResponseCode()).as("check responseCode").isEqualTo(expected.getResponseCode()))
            .satisfies(a -> assertThat(a.getResponseBody()).as("check responseBody").isEqualTo(expected.getResponseBody()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiIdempotencyKeyUpdatableRelationshipsEquals(ApiIdempotencyKey expected, ApiIdempotencyKey actual) {
        // empty method
    }
}
