package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigAllPropertiesEquals(AppConfig expected, AppConfig actual) {
        assertAppConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertAppConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigAllUpdatablePropertiesEquals(AppConfig expected, AppConfig actual) {
        assertAppConfigUpdatableFieldsEquals(expected, actual);
        assertAppConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigAutoGeneratedPropertiesEquals(AppConfig expected, AppConfig actual) {
        assertThat(actual)
            .as("Verify AppConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigUpdatableFieldsEquals(AppConfig expected, AppConfig actual) {
        assertThat(actual)
            .as("Verify AppConfig relevant properties")
            .satisfies(a -> assertThat(a.getConfigKey()).as("check configKey").isEqualTo(expected.getConfigKey()))
            .satisfies(a -> assertThat(a.getConfigValue()).as("check configValue").isEqualTo(expected.getConfigValue()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getUpdatedBy()).as("check updatedBy").isEqualTo(expected.getUpdatedBy()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppConfigUpdatableRelationshipsEquals(AppConfig expected, AppConfig actual) {
        // empty method
    }
}
