package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BannerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBannerAllPropertiesEquals(Banner expected, Banner actual) {
        assertBannerAutoGeneratedPropertiesEquals(expected, actual);
        assertBannerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBannerAllUpdatablePropertiesEquals(Banner expected, Banner actual) {
        assertBannerUpdatableFieldsEquals(expected, actual);
        assertBannerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBannerAutoGeneratedPropertiesEquals(Banner expected, Banner actual) {
        assertThat(actual)
            .as("Verify Banner auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBannerUpdatableFieldsEquals(Banner expected, Banner actual) {
        assertThat(actual)
            .as("Verify Banner relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getDeepLink()).as("check deepLink").isEqualTo(expected.getDeepLink()))
            .satisfies(a -> assertThat(a.getPlacement()).as("check placement").isEqualTo(expected.getPlacement()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getStartsAt()).as("check startsAt").isEqualTo(expected.getStartsAt()))
            .satisfies(a -> assertThat(a.getEndsAt()).as("check endsAt").isEqualTo(expected.getEndsAt()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBannerUpdatableRelationshipsEquals(Banner expected, Banner actual) {
        assertThat(actual)
            .as("Verify Banner relationships")
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()));
    }
}
