package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BlockedEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedEntityAllPropertiesEquals(BlockedEntity expected, BlockedEntity actual) {
        assertBlockedEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertBlockedEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedEntityAllUpdatablePropertiesEquals(BlockedEntity expected, BlockedEntity actual) {
        assertBlockedEntityUpdatableFieldsEquals(expected, actual);
        assertBlockedEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedEntityAutoGeneratedPropertiesEquals(BlockedEntity expected, BlockedEntity actual) {
        assertThat(actual)
            .as("Verify BlockedEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedEntityUpdatableFieldsEquals(BlockedEntity expected, BlockedEntity actual) {
        assertThat(actual)
            .as("Verify BlockedEntity relevant properties")
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getValueHash()).as("check valueHash").isEqualTo(expected.getValueHash()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getBlockedUntil()).as("check blockedUntil").isEqualTo(expected.getBlockedUntil()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedEntityUpdatableRelationshipsEquals(BlockedEntity expected, BlockedEntity actual) {
        // empty method
    }
}
