package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusHistoryAllPropertiesEquals(BookingStatusHistory expected, BookingStatusHistory actual) {
        assertBookingStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusHistoryAllUpdatablePropertiesEquals(BookingStatusHistory expected, BookingStatusHistory actual) {
        assertBookingStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertBookingStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusHistoryAutoGeneratedPropertiesEquals(BookingStatusHistory expected, BookingStatusHistory actual) {
        assertThat(actual)
            .as("Verify BookingStatusHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusHistoryUpdatableFieldsEquals(BookingStatusHistory expected, BookingStatusHistory actual) {
        assertThat(actual)
            .as("Verify BookingStatusHistory relevant properties")
            .satisfies(a -> assertThat(a.getFromStatus()).as("check fromStatus").isEqualTo(expected.getFromStatus()))
            .satisfies(a -> assertThat(a.getToStatus()).as("check toStatus").isEqualTo(expected.getToStatus()))
            .satisfies(a -> assertThat(a.getChangedBy()).as("check changedBy").isEqualTo(expected.getChangedBy()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusHistoryUpdatableRelationshipsEquals(BookingStatusHistory expected, BookingStatusHistory actual) {
        assertThat(actual)
            .as("Verify BookingStatusHistory relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
