package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingMediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingMediaAllPropertiesEquals(BookingMedia expected, BookingMedia actual) {
        assertBookingMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingMediaAllUpdatablePropertiesEquals(BookingMedia expected, BookingMedia actual) {
        assertBookingMediaUpdatableFieldsEquals(expected, actual);
        assertBookingMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingMediaAutoGeneratedPropertiesEquals(BookingMedia expected, BookingMedia actual) {
        assertThat(actual)
            .as("Verify BookingMedia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingMediaUpdatableFieldsEquals(BookingMedia expected, BookingMedia actual) {
        assertThat(actual)
            .as("Verify BookingMedia relevant properties")
            .satisfies(a -> assertThat(a.getMediaType()).as("check mediaType").isEqualTo(expected.getMediaType()))
            .satisfies(a -> assertThat(a.getFileUrl()).as("check fileUrl").isEqualTo(expected.getFileUrl()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingMediaUpdatableRelationshipsEquals(BookingMedia expected, BookingMedia actual) {
        assertThat(actual)
            .as("Verify BookingMedia relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
