package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAssignmentAllPropertiesEquals(BookingAssignment expected, BookingAssignment actual) {
        assertBookingAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAssignmentAllUpdatablePropertiesEquals(BookingAssignment expected, BookingAssignment actual) {
        assertBookingAssignmentUpdatableFieldsEquals(expected, actual);
        assertBookingAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAssignmentAutoGeneratedPropertiesEquals(BookingAssignment expected, BookingAssignment actual) {
        assertThat(actual)
            .as("Verify BookingAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAssignmentUpdatableFieldsEquals(BookingAssignment expected, BookingAssignment actual) {
        assertThat(actual)
            .as("Verify BookingAssignment relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getOfferedAt()).as("check offeredAt").isEqualTo(expected.getOfferedAt()))
            .satisfies(a -> assertThat(a.getRespondedAt()).as("check respondedAt").isEqualTo(expected.getRespondedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getRejectReason()).as("check rejectReason").isEqualTo(expected.getRejectReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAssignmentUpdatableRelationshipsEquals(BookingAssignment expected, BookingAssignment actual) {
        assertThat(actual)
            .as("Verify BookingAssignment relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
