package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingSubscriptionAllPropertiesEquals(BookingSubscription expected, BookingSubscription actual) {
        assertBookingSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingSubscriptionAllUpdatablePropertiesEquals(BookingSubscription expected, BookingSubscription actual) {
        assertBookingSubscriptionUpdatableFieldsEquals(expected, actual);
        assertBookingSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingSubscriptionAutoGeneratedPropertiesEquals(BookingSubscription expected, BookingSubscription actual) {
        assertThat(actual)
            .as("Verify BookingSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingSubscriptionUpdatableFieldsEquals(BookingSubscription expected, BookingSubscription actual) {
        assertThat(actual)
            .as("Verify BookingSubscription relevant properties")
            .satisfies(a -> assertThat(a.getFrequency()).as("check frequency").isEqualTo(expected.getFrequency()))
            .satisfies(a -> assertThat(a.getDaysOfWeek()).as("check daysOfWeek").isEqualTo(expected.getDaysOfWeek()))
            .satisfies(a -> assertThat(a.getPreferredTime()).as("check preferredTime").isEqualTo(expected.getPreferredTime()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getNextRunDate()).as("check nextRunDate").isEqualTo(expected.getNextRunDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAutoPay()).as("check autoPay").isEqualTo(expected.getAutoPay()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingSubscriptionUpdatableRelationshipsEquals(BookingSubscription expected, BookingSubscription actual) {
        assertThat(actual)
            .as("Verify BookingSubscription relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getServicePackage()).as("check servicePackage").isEqualTo(expected.getServicePackage()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a ->
                assertThat(a.getPreferredProfessional()).as("check preferredProfessional").isEqualTo(expected.getPreferredProfessional())
            );
    }
}
