package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BookingQuoteItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteItemAllPropertiesEquals(BookingQuoteItem expected, BookingQuoteItem actual) {
        assertBookingQuoteItemAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingQuoteItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteItemAllUpdatablePropertiesEquals(BookingQuoteItem expected, BookingQuoteItem actual) {
        assertBookingQuoteItemUpdatableFieldsEquals(expected, actual);
        assertBookingQuoteItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteItemAutoGeneratedPropertiesEquals(BookingQuoteItem expected, BookingQuoteItem actual) {
        assertThat(actual)
            .as("Verify BookingQuoteItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteItemUpdatableFieldsEquals(BookingQuoteItem expected, BookingQuoteItem actual) {
        assertThat(actual)
            .as("Verify BookingQuoteItem relevant properties")
            .satisfies(a -> assertThat(a.getItemType()).as("check itemType").isEqualTo(expected.getItemType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getLineTotal()).as("check lineTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLineTotal())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteItemUpdatableRelationshipsEquals(BookingQuoteItem expected, BookingQuoteItem actual) {
        assertThat(actual)
            .as("Verify BookingQuoteItem relationships")
            .satisfies(a -> assertThat(a.getQuote()).as("check quote").isEqualTo(expected.getQuote()));
    }
}
