package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BookingItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemAllPropertiesEquals(BookingItem expected, BookingItem actual) {
        assertBookingItemAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemAllUpdatablePropertiesEquals(BookingItem expected, BookingItem actual) {
        assertBookingItemUpdatableFieldsEquals(expected, actual);
        assertBookingItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemAutoGeneratedPropertiesEquals(BookingItem expected, BookingItem actual) {
        assertThat(actual)
            .as("Verify BookingItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemUpdatableFieldsEquals(BookingItem expected, BookingItem actual) {
        assertThat(actual)
            .as("Verify BookingItem relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getLineTotal()).as("check lineTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLineTotal())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingItemUpdatableRelationshipsEquals(BookingItem expected, BookingItem actual) {
        assertThat(actual)
            .as("Verify BookingItem relationships")
            .satisfies(a -> assertThat(a.getServicePackage()).as("check servicePackage").isEqualTo(expected.getServicePackage()))
            .satisfies(a -> assertThat(a.getAddon()).as("check addon").isEqualTo(expected.getAddon()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
