package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BookingRescheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingRescheduleAllPropertiesEquals(BookingReschedule expected, BookingReschedule actual) {
        assertBookingRescheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingRescheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingRescheduleAllUpdatablePropertiesEquals(BookingReschedule expected, BookingReschedule actual) {
        assertBookingRescheduleUpdatableFieldsEquals(expected, actual);
        assertBookingRescheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingRescheduleAutoGeneratedPropertiesEquals(BookingReschedule expected, BookingReschedule actual) {
        assertThat(actual)
            .as("Verify BookingReschedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingRescheduleUpdatableFieldsEquals(BookingReschedule expected, BookingReschedule actual) {
        assertThat(actual)
            .as("Verify BookingReschedule relevant properties")
            .satisfies(a -> assertThat(a.getOldStart()).as("check oldStart").isEqualTo(expected.getOldStart()))
            .satisfies(a -> assertThat(a.getOldEnd()).as("check oldEnd").isEqualTo(expected.getOldEnd()))
            .satisfies(a -> assertThat(a.getNewStart()).as("check newStart").isEqualTo(expected.getNewStart()))
            .satisfies(a -> assertThat(a.getNewEnd()).as("check newEnd").isEqualTo(expected.getNewEnd()))
            .satisfies(a -> assertThat(a.getRequestedBy()).as("check requestedBy").isEqualTo(expected.getRequestedBy()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a ->
                assertThat(a.getFeeCharged())
                    .as("check feeCharged")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFeeCharged())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingRescheduleUpdatableRelationshipsEquals(BookingReschedule expected, BookingReschedule actual) {
        assertThat(actual)
            .as("Verify BookingReschedule relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
