package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BookingQuoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteAllPropertiesEquals(BookingQuote expected, BookingQuote actual) {
        assertBookingQuoteAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingQuoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteAllUpdatablePropertiesEquals(BookingQuote expected, BookingQuote actual) {
        assertBookingQuoteUpdatableFieldsEquals(expected, actual);
        assertBookingQuoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteAutoGeneratedPropertiesEquals(BookingQuote expected, BookingQuote actual) {
        assertThat(actual)
            .as("Verify BookingQuote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteUpdatableFieldsEquals(BookingQuote expected, BookingQuote actual) {
        assertThat(actual)
            .as("Verify BookingQuote relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getValidUntil()).as("check validUntil").isEqualTo(expected.getValidUntil()))
            .satisfies(a -> assertThat(a.getRespondedAt()).as("check respondedAt").isEqualTo(expected.getRespondedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingQuoteUpdatableRelationshipsEquals(BookingQuote expected, BookingQuote actual) {
        assertThat(actual)
            .as("Verify BookingQuote relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
