package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BookingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAllPropertiesEquals(Booking expected, Booking actual) {
        assertBookingAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAllUpdatablePropertiesEquals(Booking expected, Booking actual) {
        assertBookingUpdatableFieldsEquals(expected, actual);
        assertBookingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAutoGeneratedPropertiesEquals(Booking expected, Booking actual) {
        assertThat(actual)
            .as("Verify Booking auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingUpdatableFieldsEquals(Booking expected, Booking actual) {
        assertThat(actual)
            .as("Verify Booking relevant properties")
            .satisfies(a -> assertThat(a.getBookingNo()).as("check bookingNo").isEqualTo(expected.getBookingNo()))
            .satisfies(a -> assertThat(a.getPublicId()).as("check publicId").isEqualTo(expected.getPublicId()))
            .satisfies(a -> assertThat(a.getServiceTitle()).as("check serviceTitle").isEqualTo(expected.getServiceTitle()))
            .satisfies(a -> assertThat(a.getAddressSnapshot()).as("check addressSnapshot").isEqualTo(expected.getAddressSnapshot()))
            .satisfies(a -> assertThat(a.getScheduledStart()).as("check scheduledStart").isEqualTo(expected.getScheduledStart()))
            .satisfies(a -> assertThat(a.getScheduledEnd()).as("check scheduledEnd").isEqualTo(expected.getScheduledEnd()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPaymentStatus()).as("check paymentStatus").isEqualTo(expected.getPaymentStatus()))
            .satisfies(a -> assertThat(a.getPaymentMode()).as("check paymentMode").isEqualTo(expected.getPaymentMode()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getAddonTotal())
                    .as("check addonTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAddonTotal())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getServiceFee())
                    .as("check serviceFee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getServiceFee())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a ->
                assertThat(a.getTipAmount()).as("check tipAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTipAmount())
            )
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getCustomerNotes()).as("check customerNotes").isEqualTo(expected.getCustomerNotes()))
            .satisfies(a -> assertThat(a.getStartOtp()).as("check startOtp").isEqualTo(expected.getStartOtp()))
            .satisfies(a -> assertThat(a.getCancelledBy()).as("check cancelledBy").isEqualTo(expected.getCancelledBy()))
            .satisfies(a -> assertThat(a.getCancelReason()).as("check cancelReason").isEqualTo(expected.getCancelReason()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a ->
                assertThat(a.getWalletAmountUsed())
                    .as("check walletAmountUsed")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getWalletAmountUsed())
            )
            .satisfies(a -> assertThat(a.getLoyaltyPointsUsed()).as("check loyaltyPointsUsed").isEqualTo(expected.getLoyaltyPointsUsed()))
            .satisfies(a ->
                assertThat(a.getCancellationFee())
                    .as("check cancellationFee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCancellationFee())
            )
            .satisfies(a -> assertThat(a.getRescheduleCount()).as("check rescheduleCount").isEqualTo(expected.getRescheduleCount()))
            .satisfies(a ->
                assertThat(a.getPlatformCommission())
                    .as("check platformCommission")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPlatformCommission())
            )
            .satisfies(a ->
                assertThat(a.getProEarning())
                    .as("check proEarning")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getProEarning())
            )
            .satisfies(a -> assertThat(a.getArrivalEta()).as("check arrivalEta").isEqualTo(expected.getArrivalEta()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getCancelledAt()).as("check cancelledAt").isEqualTo(expected.getCancelledAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingUpdatableRelationshipsEquals(Booking expected, Booking actual) {
        assertThat(actual)
            .as("Verify Booking relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getCoupon()).as("check coupon").isEqualTo(expected.getCoupon()))
            .satisfies(a -> assertThat(a.getSubscription()).as("check subscription").isEqualTo(expected.getSubscription()))
            .satisfies(a -> assertThat(a.getSlotCapacity()).as("check slotCapacity").isEqualTo(expected.getSlotCapacity()));
    }
}
