package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CallSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCallSessionAllPropertiesEquals(CallSession expected, CallSession actual) {
        assertCallSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertCallSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCallSessionAllUpdatablePropertiesEquals(CallSession expected, CallSession actual) {
        assertCallSessionUpdatableFieldsEquals(expected, actual);
        assertCallSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCallSessionAutoGeneratedPropertiesEquals(CallSession expected, CallSession actual) {
        assertThat(actual)
            .as("Verify CallSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCallSessionUpdatableFieldsEquals(CallSession expected, CallSession actual) {
        assertThat(actual)
            .as("Verify CallSession relevant properties")
            .satisfies(a -> assertThat(a.getVirtualNumber()).as("check virtualNumber").isEqualTo(expected.getVirtualNumber()))
            .satisfies(a -> assertThat(a.getProviderCallId()).as("check providerCallId").isEqualTo(expected.getProviderCallId()))
            .satisfies(a -> assertThat(a.getDurationSec()).as("check durationSec").isEqualTo(expected.getDurationSec()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCallSessionUpdatableRelationshipsEquals(CallSession expected, CallSession actual) {
        assertThat(actual)
            .as("Verify CallSession relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
