package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CancellationPolicyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCancellationPolicyAllPropertiesEquals(CancellationPolicy expected, CancellationPolicy actual) {
        assertCancellationPolicyAutoGeneratedPropertiesEquals(expected, actual);
        assertCancellationPolicyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCancellationPolicyAllUpdatablePropertiesEquals(CancellationPolicy expected, CancellationPolicy actual) {
        assertCancellationPolicyUpdatableFieldsEquals(expected, actual);
        assertCancellationPolicyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCancellationPolicyAutoGeneratedPropertiesEquals(CancellationPolicy expected, CancellationPolicy actual) {
        assertThat(actual)
            .as("Verify CancellationPolicy auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCancellationPolicyUpdatableFieldsEquals(CancellationPolicy expected, CancellationPolicy actual) {
        assertThat(actual)
            .as("Verify CancellationPolicy relevant properties")
            .satisfies(a -> assertThat(a.getHoursBeforeStart()).as("check hoursBeforeStart").isEqualTo(expected.getHoursBeforeStart()))
            .satisfies(a ->
                assertThat(a.getFeePercent())
                    .as("check feePercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFeePercent())
            )
            .satisfies(a ->
                assertThat(a.getMinFee()).as("check minFee").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMinFee())
            )
            .satisfies(a -> assertThat(a.getAppliesTo()).as("check appliesTo").isEqualTo(expected.getAppliesTo()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCancellationPolicyUpdatableRelationshipsEquals(CancellationPolicy expected, CancellationPolicy actual) {
        assertThat(actual)
            .as("Verify CancellationPolicy relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
