package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatThreadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatThreadAllPropertiesEquals(ChatThread expected, ChatThread actual) {
        assertChatThreadAutoGeneratedPropertiesEquals(expected, actual);
        assertChatThreadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatThreadAllUpdatablePropertiesEquals(ChatThread expected, ChatThread actual) {
        assertChatThreadUpdatableFieldsEquals(expected, actual);
        assertChatThreadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatThreadAutoGeneratedPropertiesEquals(ChatThread expected, ChatThread actual) {
        assertThat(actual)
            .as("Verify ChatThread auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatThreadUpdatableFieldsEquals(ChatThread expected, ChatThread actual) {
        assertThat(actual)
            .as("Verify ChatThread relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatThreadUpdatableRelationshipsEquals(ChatThread expected, ChatThread actual) {
        assertThat(actual)
            .as("Verify ChatThread relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()))
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
