package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CityDailyMetricsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityDailyMetricsAllPropertiesEquals(CityDailyMetrics expected, CityDailyMetrics actual) {
        assertCityDailyMetricsAutoGeneratedPropertiesEquals(expected, actual);
        assertCityDailyMetricsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityDailyMetricsAllUpdatablePropertiesEquals(CityDailyMetrics expected, CityDailyMetrics actual) {
        assertCityDailyMetricsUpdatableFieldsEquals(expected, actual);
        assertCityDailyMetricsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityDailyMetricsAutoGeneratedPropertiesEquals(CityDailyMetrics expected, CityDailyMetrics actual) {
        assertThat(actual)
            .as("Verify CityDailyMetrics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityDailyMetricsUpdatableFieldsEquals(CityDailyMetrics expected, CityDailyMetrics actual) {
        assertThat(actual)
            .as("Verify CityDailyMetrics relevant properties")
            .satisfies(a -> assertThat(a.getMetricDate()).as("check metricDate").isEqualTo(expected.getMetricDate()))
            .satisfies(a -> assertThat(a.getBookingsCreated()).as("check bookingsCreated").isEqualTo(expected.getBookingsCreated()))
            .satisfies(a -> assertThat(a.getBookingsCompleted()).as("check bookingsCompleted").isEqualTo(expected.getBookingsCompleted()))
            .satisfies(a -> assertThat(a.getBookingsCancelled()).as("check bookingsCancelled").isEqualTo(expected.getBookingsCancelled()))
            .satisfies(a -> assertThat(a.getGmv()).as("check gmv").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getGmv()))
            .satisfies(a ->
                assertThat(a.getPlatformRevenue())
                    .as("check platformRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPlatformRevenue())
            )
            .satisfies(a -> assertThat(a.getAvgRating()).as("check avgRating").isEqualTo(expected.getAvgRating()))
            .satisfies(a -> assertThat(a.getAvgAssignmentSec()).as("check avgAssignmentSec").isEqualTo(expected.getAvgAssignmentSec()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityDailyMetricsUpdatableRelationshipsEquals(CityDailyMetrics expected, CityDailyMetrics actual) {
        assertThat(actual)
            .as("Verify CityDailyMetrics relationships")
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
