package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CityPackagePriceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityPackagePriceAllPropertiesEquals(CityPackagePrice expected, CityPackagePrice actual) {
        assertCityPackagePriceAutoGeneratedPropertiesEquals(expected, actual);
        assertCityPackagePriceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityPackagePriceAllUpdatablePropertiesEquals(CityPackagePrice expected, CityPackagePrice actual) {
        assertCityPackagePriceUpdatableFieldsEquals(expected, actual);
        assertCityPackagePriceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityPackagePriceAutoGeneratedPropertiesEquals(CityPackagePrice expected, CityPackagePrice actual) {
        assertThat(actual)
            .as("Verify CityPackagePrice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityPackagePriceUpdatableFieldsEquals(CityPackagePrice expected, CityPackagePrice actual) {
        assertThat(actual)
            .as("Verify CityPackagePrice relevant properties")
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a ->
                assertThat(a.getSurgeMultiplier())
                    .as("check surgeMultiplier")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSurgeMultiplier())
            )
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidTo()).as("check validTo").isEqualTo(expected.getValidTo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityPackagePriceUpdatableRelationshipsEquals(CityPackagePrice expected, CityPackagePrice actual) {
        assertThat(actual)
            .as("Verify CityPackagePrice relationships")
            .satisfies(a -> assertThat(a.getServicePackage()).as("check servicePackage").isEqualTo(expected.getServicePackage()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()));
    }
}
