package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CommissionRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleAllPropertiesEquals(CommissionRule expected, CommissionRule actual) {
        assertCommissionRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertCommissionRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleAllUpdatablePropertiesEquals(CommissionRule expected, CommissionRule actual) {
        assertCommissionRuleUpdatableFieldsEquals(expected, actual);
        assertCommissionRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleAutoGeneratedPropertiesEquals(CommissionRule expected, CommissionRule actual) {
        assertThat(actual)
            .as("Verify CommissionRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleUpdatableFieldsEquals(CommissionRule expected, CommissionRule actual) {
        assertThat(actual)
            .as("Verify CommissionRule relevant properties")
            .satisfies(a ->
                assertThat(a.getCommissionPercent())
                    .as("check commissionPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCommissionPercent())
            )
            .satisfies(a ->
                assertThat(a.getFlatFee()).as("check flatFee").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFlatFee())
            )
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidTo()).as("check validTo").isEqualTo(expected.getValidTo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommissionRuleUpdatableRelationshipsEquals(CommissionRule expected, CommissionRule actual) {
        assertThat(actual)
            .as("Verify CommissionRule relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getTier()).as("check tier").isEqualTo(expected.getTier()));
    }
}
