package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CouponRedemptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponRedemptionAllPropertiesEquals(CouponRedemption expected, CouponRedemption actual) {
        assertCouponRedemptionAutoGeneratedPropertiesEquals(expected, actual);
        assertCouponRedemptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponRedemptionAllUpdatablePropertiesEquals(CouponRedemption expected, CouponRedemption actual) {
        assertCouponRedemptionUpdatableFieldsEquals(expected, actual);
        assertCouponRedemptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponRedemptionAutoGeneratedPropertiesEquals(CouponRedemption expected, CouponRedemption actual) {
        assertThat(actual)
            .as("Verify CouponRedemption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponRedemptionUpdatableFieldsEquals(CouponRedemption expected, CouponRedemption actual) {
        assertThat(actual)
            .as("Verify CouponRedemption relevant properties")
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponRedemptionUpdatableRelationshipsEquals(CouponRedemption expected, CouponRedemption actual) {
        assertThat(actual)
            .as("Verify CouponRedemption relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()))
            .satisfies(a -> assertThat(a.getCoupon()).as("check coupon").isEqualTo(expected.getCoupon()));
    }
}
