package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CouponAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponAllPropertiesEquals(Coupon expected, Coupon actual) {
        assertCouponAutoGeneratedPropertiesEquals(expected, actual);
        assertCouponAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponAllUpdatablePropertiesEquals(Coupon expected, Coupon actual) {
        assertCouponUpdatableFieldsEquals(expected, actual);
        assertCouponUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponAutoGeneratedPropertiesEquals(Coupon expected, Coupon actual) {
        assertThat(actual)
            .as("Verify Coupon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponUpdatableFieldsEquals(Coupon expected, Coupon actual) {
        assertThat(actual)
            .as("Verify Coupon relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDiscountType()).as("check discountType").isEqualTo(expected.getDiscountType()))
            .satisfies(a ->
                assertThat(a.getDiscountValue())
                    .as("check discountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountValue())
            )
            .satisfies(a ->
                assertThat(a.getMaxDiscount())
                    .as("check maxDiscount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMaxDiscount())
            )
            .satisfies(a ->
                assertThat(a.getMinOrderValue())
                    .as("check minOrderValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMinOrderValue())
            )
            .satisfies(a -> assertThat(a.getFirstBookingOnly()).as("check firstBookingOnly").isEqualTo(expected.getFirstBookingOnly()))
            .satisfies(a -> assertThat(a.getTotalUsageLimit()).as("check totalUsageLimit").isEqualTo(expected.getTotalUsageLimit()))
            .satisfies(a -> assertThat(a.getPerUserLimit()).as("check perUserLimit").isEqualTo(expected.getPerUserLimit()))
            .satisfies(a -> assertThat(a.getUsedCount()).as("check usedCount").isEqualTo(expected.getUsedCount()))
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidTo()).as("check validTo").isEqualTo(expected.getValidTo()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouponUpdatableRelationshipsEquals(Coupon expected, Coupon actual) {
        assertThat(actual)
            .as("Verify Coupon relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()));
    }
}
