package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CustomerWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletAllPropertiesEquals(CustomerWallet expected, CustomerWallet actual) {
        assertCustomerWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletAllUpdatablePropertiesEquals(CustomerWallet expected, CustomerWallet actual) {
        assertCustomerWalletUpdatableFieldsEquals(expected, actual);
        assertCustomerWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletAutoGeneratedPropertiesEquals(CustomerWallet expected, CustomerWallet actual) {
        assertThat(actual)
            .as("Verify CustomerWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletUpdatableFieldsEquals(CustomerWallet expected, CustomerWallet actual) {
        assertThat(actual)
            .as("Verify CustomerWallet relevant properties")
            .satisfies(a ->
                assertThat(a.getBalance()).as("check balance").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBalance())
            )
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletUpdatableRelationshipsEquals(CustomerWallet expected, CustomerWallet actual) {
        // empty method
    }
}
