package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomerAddressAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerAddressAllPropertiesEquals(CustomerAddress expected, CustomerAddress actual) {
        assertCustomerAddressAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerAddressAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerAddressAllUpdatablePropertiesEquals(CustomerAddress expected, CustomerAddress actual) {
        assertCustomerAddressUpdatableFieldsEquals(expected, actual);
        assertCustomerAddressUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerAddressAutoGeneratedPropertiesEquals(CustomerAddress expected, CustomerAddress actual) {
        assertThat(actual)
            .as("Verify CustomerAddress auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerAddressUpdatableFieldsEquals(CustomerAddress expected, CustomerAddress actual) {
        assertThat(actual)
            .as("Verify CustomerAddress relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getContactName()).as("check contactName").isEqualTo(expected.getContactName()))
            .satisfies(a -> assertThat(a.getContactPhone()).as("check contactPhone").isEqualTo(expected.getContactPhone()))
            .satisfies(a -> assertThat(a.getLine1()).as("check line1").isEqualTo(expected.getLine1()))
            .satisfies(a -> assertThat(a.getLine2()).as("check line2").isEqualTo(expected.getLine2()))
            .satisfies(a -> assertThat(a.getLandmark()).as("check landmark").isEqualTo(expected.getLandmark()))
            .satisfies(a -> assertThat(a.getPincode()).as("check pincode").isEqualTo(expected.getPincode()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getDefaultAddress()).as("check defaultAddress").isEqualTo(expected.getDefaultAddress()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerAddressUpdatableRelationshipsEquals(CustomerAddress expected, CustomerAddress actual) {
        assertThat(actual)
            .as("Verify CustomerAddress relationships")
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()));
    }
}
