package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CustomerWalletTxnAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletTxnAllPropertiesEquals(CustomerWalletTxn expected, CustomerWalletTxn actual) {
        assertCustomerWalletTxnAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerWalletTxnAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletTxnAllUpdatablePropertiesEquals(CustomerWalletTxn expected, CustomerWalletTxn actual) {
        assertCustomerWalletTxnUpdatableFieldsEquals(expected, actual);
        assertCustomerWalletTxnUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletTxnAutoGeneratedPropertiesEquals(CustomerWalletTxn expected, CustomerWalletTxn actual) {
        assertThat(actual)
            .as("Verify CustomerWalletTxn auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletTxnUpdatableFieldsEquals(CustomerWalletTxn expected, CustomerWalletTxn actual) {
        assertThat(actual)
            .as("Verify CustomerWalletTxn relevant properties")
            .satisfies(a -> assertThat(a.getTxnType()).as("check txnType").isEqualTo(expected.getTxnType()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a ->
                assertThat(a.getBalanceAfter())
                    .as("check balanceAfter")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBalanceAfter())
            )
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerWalletTxnUpdatableRelationshipsEquals(CustomerWalletTxn expected, CustomerWalletTxn actual) {
        assertThat(actual)
            .as("Verify CustomerWalletTxn relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
