package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DataDeletionRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataDeletionRequestAllPropertiesEquals(DataDeletionRequest expected, DataDeletionRequest actual) {
        assertDataDeletionRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertDataDeletionRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataDeletionRequestAllUpdatablePropertiesEquals(DataDeletionRequest expected, DataDeletionRequest actual) {
        assertDataDeletionRequestUpdatableFieldsEquals(expected, actual);
        assertDataDeletionRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataDeletionRequestAutoGeneratedPropertiesEquals(DataDeletionRequest expected, DataDeletionRequest actual) {
        assertThat(actual)
            .as("Verify DataDeletionRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataDeletionRequestUpdatableFieldsEquals(DataDeletionRequest expected, DataDeletionRequest actual) {
        assertThat(actual)
            .as("Verify DataDeletionRequest relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDataDeletionRequestUpdatableRelationshipsEquals(DataDeletionRequest expected, DataDeletionRequest actual) {
        // empty method
    }
}
