package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeviceTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviceTokenAllPropertiesEquals(DeviceToken expected, DeviceToken actual) {
        assertDeviceTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertDeviceTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviceTokenAllUpdatablePropertiesEquals(DeviceToken expected, DeviceToken actual) {
        assertDeviceTokenUpdatableFieldsEquals(expected, actual);
        assertDeviceTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviceTokenAutoGeneratedPropertiesEquals(DeviceToken expected, DeviceToken actual) {
        assertThat(actual)
            .as("Verify DeviceToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviceTokenUpdatableFieldsEquals(DeviceToken expected, DeviceToken actual) {
        assertThat(actual)
            .as("Verify DeviceToken relevant properties")
            .satisfies(a -> assertThat(a.getPlatform()).as("check platform").isEqualTo(expected.getPlatform()))
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeviceTokenUpdatableRelationshipsEquals(DeviceToken expected, DeviceToken actual) {
        // empty method
    }
}
