package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FacilityServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityServiceAllPropertiesEquals(FacilityService expected, FacilityService actual) {
        assertFacilityServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertFacilityServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityServiceAllUpdatablePropertiesEquals(FacilityService expected, FacilityService actual) {
        assertFacilityServiceUpdatableFieldsEquals(expected, actual);
        assertFacilityServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityServiceAutoGeneratedPropertiesEquals(FacilityService expected, FacilityService actual) {
        assertThat(actual)
            .as("Verify FacilityService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityServiceUpdatableFieldsEquals(FacilityService expected, FacilityService actual) {
        assertThat(actual)
            .as("Verify FacilityService relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getEmoji()).as("check emoji").isEqualTo(expected.getEmoji()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getHighlights()).as("check highlights").isEqualTo(expected.getHighlights()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getWarrantyDays()).as("check warrantyDays").isEqualTo(expected.getWarrantyDays()))
            .satisfies(a -> assertThat(a.getSacCode()).as("check sacCode").isEqualTo(expected.getSacCode()))
            .satisfies(a ->
                assertThat(a.getGstPercent())
                    .as("check gstPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getGstPercent())
            )
            .satisfies(a -> assertThat(a.getGenderSpecific()).as("check genderSpecific").isEqualTo(expected.getGenderSpecific()))
            .satisfies(a ->
                assertThat(a.getRequiresVisitCharge()).as("check requiresVisitCharge").isEqualTo(expected.getRequiresVisitCharge())
            )
            .satisfies(a -> assertThat(a.getPopular()).as("check popular").isEqualTo(expected.getPopular()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getAvgRating()).as("check avgRating").isEqualTo(expected.getAvgRating()))
            .satisfies(a -> assertThat(a.getReviewsCount()).as("check reviewsCount").isEqualTo(expected.getReviewsCount()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityServiceUpdatableRelationshipsEquals(FacilityService expected, FacilityService actual) {
        assertThat(actual)
            .as("Verify FacilityService relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
