package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeatureFlagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureFlagAllPropertiesEquals(FeatureFlag expected, FeatureFlag actual) {
        assertFeatureFlagAutoGeneratedPropertiesEquals(expected, actual);
        assertFeatureFlagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureFlagAllUpdatablePropertiesEquals(FeatureFlag expected, FeatureFlag actual) {
        assertFeatureFlagUpdatableFieldsEquals(expected, actual);
        assertFeatureFlagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureFlagAutoGeneratedPropertiesEquals(FeatureFlag expected, FeatureFlag actual) {
        assertThat(actual)
            .as("Verify FeatureFlag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureFlagUpdatableFieldsEquals(FeatureFlag expected, FeatureFlag actual) {
        assertThat(actual)
            .as("Verify FeatureFlag relevant properties")
            .satisfies(a -> assertThat(a.getFlagKey()).as("check flagKey").isEqualTo(expected.getFlagKey()))
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()))
            .satisfies(a -> assertThat(a.getRolloutPercent()).as("check rolloutPercent").isEqualTo(expected.getRolloutPercent()))
            .satisfies(a -> assertThat(a.getCityIds()).as("check cityIds").isEqualTo(expected.getCityIds()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeatureFlagUpdatableRelationshipsEquals(FeatureFlag expected, FeatureFlag actual) {
        // empty method
    }
}
