package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FraudFlagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFraudFlagAllPropertiesEquals(FraudFlag expected, FraudFlag actual) {
        assertFraudFlagAutoGeneratedPropertiesEquals(expected, actual);
        assertFraudFlagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFraudFlagAllUpdatablePropertiesEquals(FraudFlag expected, FraudFlag actual) {
        assertFraudFlagUpdatableFieldsEquals(expected, actual);
        assertFraudFlagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFraudFlagAutoGeneratedPropertiesEquals(FraudFlag expected, FraudFlag actual) {
        assertThat(actual)
            .as("Verify FraudFlag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFraudFlagUpdatableFieldsEquals(FraudFlag expected, FraudFlag actual) {
        assertThat(actual)
            .as("Verify FraudFlag relevant properties")
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getRuleCode()).as("check ruleCode").isEqualTo(expected.getRuleCode()))
            .satisfies(a -> assertThat(a.getRiskScore()).as("check riskScore").isEqualTo(expected.getRiskScore()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFraudFlagUpdatableRelationshipsEquals(FraudFlag expected, FraudFlag actual) {
        // empty method
    }
}
