package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class IncentiveRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncentiveRuleAllPropertiesEquals(IncentiveRule expected, IncentiveRule actual) {
        assertIncentiveRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertIncentiveRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncentiveRuleAllUpdatablePropertiesEquals(IncentiveRule expected, IncentiveRule actual) {
        assertIncentiveRuleUpdatableFieldsEquals(expected, actual);
        assertIncentiveRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncentiveRuleAutoGeneratedPropertiesEquals(IncentiveRule expected, IncentiveRule actual) {
        assertThat(actual)
            .as("Verify IncentiveRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncentiveRuleUpdatableFieldsEquals(IncentiveRule expected, IncentiveRule actual) {
        assertThat(actual)
            .as("Verify IncentiveRule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMetric()).as("check metric").isEqualTo(expected.getMetric()))
            .satisfies(a ->
                assertThat(a.getThreshold()).as("check threshold").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getThreshold())
            )
            .satisfies(a ->
                assertThat(a.getRewardAmount())
                    .as("check rewardAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRewardAmount())
            )
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncentiveRuleUpdatableRelationshipsEquals(IncentiveRule expected, IncentiveRule actual) {
        assertThat(actual)
            .as("Verify IncentiveRule relationships")
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()));
    }
}
