package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceSequenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceSequenceAllPropertiesEquals(InvoiceSequence expected, InvoiceSequence actual) {
        assertInvoiceSequenceAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceSequenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceSequenceAllUpdatablePropertiesEquals(InvoiceSequence expected, InvoiceSequence actual) {
        assertInvoiceSequenceUpdatableFieldsEquals(expected, actual);
        assertInvoiceSequenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceSequenceAutoGeneratedPropertiesEquals(InvoiceSequence expected, InvoiceSequence actual) {
        assertThat(actual)
            .as("Verify InvoiceSequence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceSequenceUpdatableFieldsEquals(InvoiceSequence expected, InvoiceSequence actual) {
        assertThat(actual)
            .as("Verify InvoiceSequence relevant properties")
            .satisfies(a -> assertThat(a.getSeries()).as("check series").isEqualTo(expected.getSeries()))
            .satisfies(a -> assertThat(a.getFiscalYear()).as("check fiscalYear").isEqualTo(expected.getFiscalYear()))
            .satisfies(a -> assertThat(a.getLastNumber()).as("check lastNumber").isEqualTo(expected.getLastNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceSequenceUpdatableRelationshipsEquals(InvoiceSequence expected, InvoiceSequence actual) {
        // empty method
    }
}
