package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAllPropertiesEquals(Invoice expected, Invoice actual) {
        assertInvoiceAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAllUpdatablePropertiesEquals(Invoice expected, Invoice actual) {
        assertInvoiceUpdatableFieldsEquals(expected, actual);
        assertInvoiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceAutoGeneratedPropertiesEquals(Invoice expected, Invoice actual) {
        assertThat(actual)
            .as("Verify Invoice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceUpdatableFieldsEquals(Invoice expected, Invoice actual) {
        assertThat(actual)
            .as("Verify Invoice relevant properties")
            .satisfies(a -> assertThat(a.getInvoiceNo()).as("check invoiceNo").isEqualTo(expected.getInvoiceNo()))
            .satisfies(a -> assertThat(a.getInvoiceType()).as("check invoiceType").isEqualTo(expected.getInvoiceType()))
            .satisfies(a -> assertThat(a.getCustomerGstin()).as("check customerGstin").isEqualTo(expected.getCustomerGstin()))
            .satisfies(a -> assertThat(a.getSellerGstin()).as("check sellerGstin").isEqualTo(expected.getSellerGstin()))
            .satisfies(a -> assertThat(a.getPlaceOfSupply()).as("check placeOfSupply").isEqualTo(expected.getPlaceOfSupply()))
            .satisfies(a ->
                assertThat(a.getTaxableAmount())
                    .as("check taxableAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTaxableAmount())
            )
            .satisfies(a -> assertThat(a.getCgst()).as("check cgst").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCgst()))
            .satisfies(a -> assertThat(a.getSgst()).as("check sgst").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSgst()))
            .satisfies(a -> assertThat(a.getIgst()).as("check igst").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getIgst()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a -> assertThat(a.getPdfUrl()).as("check pdfUrl").isEqualTo(expected.getPdfUrl()))
            .satisfies(a -> assertThat(a.getIssuedAt()).as("check issuedAt").isEqualTo(expected.getIssuedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceUpdatableRelationshipsEquals(Invoice expected, Invoice actual) {
        assertThat(actual)
            .as("Verify Invoice relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
