package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LoyaltyLedgerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyLedgerAllPropertiesEquals(LoyaltyLedger expected, LoyaltyLedger actual) {
        assertLoyaltyLedgerAutoGeneratedPropertiesEquals(expected, actual);
        assertLoyaltyLedgerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyLedgerAllUpdatablePropertiesEquals(LoyaltyLedger expected, LoyaltyLedger actual) {
        assertLoyaltyLedgerUpdatableFieldsEquals(expected, actual);
        assertLoyaltyLedgerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyLedgerAutoGeneratedPropertiesEquals(LoyaltyLedger expected, LoyaltyLedger actual) {
        assertThat(actual)
            .as("Verify LoyaltyLedger auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyLedgerUpdatableFieldsEquals(LoyaltyLedger expected, LoyaltyLedger actual) {
        assertThat(actual)
            .as("Verify LoyaltyLedger relevant properties")
            .satisfies(a -> assertThat(a.getPoints()).as("check points").isEqualTo(expected.getPoints()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoyaltyLedgerUpdatableRelationshipsEquals(LoyaltyLedger expected, LoyaltyLedger actual) {
        assertThat(actual)
            .as("Verify LoyaltyLedger relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
