package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MembershipPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipPlanAllPropertiesEquals(MembershipPlan expected, MembershipPlan actual) {
        assertMembershipPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertMembershipPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipPlanAllUpdatablePropertiesEquals(MembershipPlan expected, MembershipPlan actual) {
        assertMembershipPlanUpdatableFieldsEquals(expected, actual);
        assertMembershipPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipPlanAutoGeneratedPropertiesEquals(MembershipPlan expected, MembershipPlan actual) {
        assertThat(actual)
            .as("Verify MembershipPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipPlanUpdatableFieldsEquals(MembershipPlan expected, MembershipPlan actual) {
        assertThat(actual)
            .as("Verify MembershipPlan relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getDurationDays()).as("check durationDays").isEqualTo(expected.getDurationDays()))
            .satisfies(a ->
                assertThat(a.getDiscountPercent())
                    .as("check discountPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountPercent())
            )
            .satisfies(a -> assertThat(a.getFreeVisitCharge()).as("check freeVisitCharge").isEqualTo(expected.getFreeVisitCharge()))
            .satisfies(a -> assertThat(a.getPrioritySupport()).as("check prioritySupport").isEqualTo(expected.getPrioritySupport()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMembershipPlanUpdatableRelationshipsEquals(MembershipPlan expected, MembershipPlan actual) {
        // empty method
    }
}
