package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OutboxEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutboxEventAllPropertiesEquals(OutboxEvent expected, OutboxEvent actual) {
        assertOutboxEventAutoGeneratedPropertiesEquals(expected, actual);
        assertOutboxEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutboxEventAllUpdatablePropertiesEquals(OutboxEvent expected, OutboxEvent actual) {
        assertOutboxEventUpdatableFieldsEquals(expected, actual);
        assertOutboxEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutboxEventAutoGeneratedPropertiesEquals(OutboxEvent expected, OutboxEvent actual) {
        assertThat(actual)
            .as("Verify OutboxEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutboxEventUpdatableFieldsEquals(OutboxEvent expected, OutboxEvent actual) {
        assertThat(actual)
            .as("Verify OutboxEvent relevant properties")
            .satisfies(a -> assertThat(a.getAggregateType()).as("check aggregateType").isEqualTo(expected.getAggregateType()))
            .satisfies(a -> assertThat(a.getAggregateId()).as("check aggregateId").isEqualTo(expected.getAggregateId()))
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAttempts()).as("check attempts").isEqualTo(expected.getAttempts()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOutboxEventUpdatableRelationshipsEquals(OutboxEvent expected, OutboxEvent actual) {
        // empty method
    }
}
