package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentWebhookEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookEventAllPropertiesEquals(PaymentWebhookEvent expected, PaymentWebhookEvent actual) {
        assertPaymentWebhookEventAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentWebhookEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookEventAllUpdatablePropertiesEquals(PaymentWebhookEvent expected, PaymentWebhookEvent actual) {
        assertPaymentWebhookEventUpdatableFieldsEquals(expected, actual);
        assertPaymentWebhookEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookEventAutoGeneratedPropertiesEquals(PaymentWebhookEvent expected, PaymentWebhookEvent actual) {
        assertThat(actual)
            .as("Verify PaymentWebhookEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookEventUpdatableFieldsEquals(PaymentWebhookEvent expected, PaymentWebhookEvent actual) {
        assertThat(actual)
            .as("Verify PaymentWebhookEvent relevant properties")
            .satisfies(a -> assertThat(a.getGateway()).as("check gateway").isEqualTo(expected.getGateway()))
            .satisfies(a -> assertThat(a.getEventId()).as("check eventId").isEqualTo(expected.getEventId()))
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getSignatureOk()).as("check signatureOk").isEqualTo(expected.getSignatureOk()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getReceivedAt()).as("check receivedAt").isEqualTo(expected.getReceivedAt()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentWebhookEventUpdatableRelationshipsEquals(PaymentWebhookEvent expected, PaymentWebhookEvent actual) {
        // empty method
    }
}
