package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PayoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutAllPropertiesEquals(Payout expected, Payout actual) {
        assertPayoutAutoGeneratedPropertiesEquals(expected, actual);
        assertPayoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutAllUpdatablePropertiesEquals(Payout expected, Payout actual) {
        assertPayoutUpdatableFieldsEquals(expected, actual);
        assertPayoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutAutoGeneratedPropertiesEquals(Payout expected, Payout actual) {
        assertThat(actual)
            .as("Verify Payout auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutUpdatableFieldsEquals(Payout expected, Payout actual) {
        assertThat(actual)
            .as("Verify Payout relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getBankReference()).as("check bankReference").isEqualTo(expected.getBankReference()))
            .satisfies(a -> assertThat(a.getPeriodStart()).as("check periodStart").isEqualTo(expected.getPeriodStart()))
            .satisfies(a -> assertThat(a.getPeriodEnd()).as("check periodEnd").isEqualTo(expected.getPeriodEnd()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getPaidAt()).as("check paidAt").isEqualTo(expected.getPaidAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutUpdatableRelationshipsEquals(Payout expected, Payout actual) {
        assertThat(actual)
            .as("Verify Payout relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
