package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalLocationLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalLocationLogAllPropertiesEquals(ProfessionalLocationLog expected, ProfessionalLocationLog actual) {
        assertProfessionalLocationLogAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalLocationLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalLocationLogAllUpdatablePropertiesEquals(
        ProfessionalLocationLog expected,
        ProfessionalLocationLog actual
    ) {
        assertProfessionalLocationLogUpdatableFieldsEquals(expected, actual);
        assertProfessionalLocationLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalLocationLogAutoGeneratedPropertiesEquals(
        ProfessionalLocationLog expected,
        ProfessionalLocationLog actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalLocationLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalLocationLogUpdatableFieldsEquals(
        ProfessionalLocationLog expected,
        ProfessionalLocationLog actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalLocationLog relevant properties")
            .satisfies(a -> assertThat(a.getProfessionalId()).as("check professionalId").isEqualTo(expected.getProfessionalId()))
            .satisfies(a -> assertThat(a.getBookingRef()).as("check bookingRef").isEqualTo(expected.getBookingRef()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getSpeedKmph()).as("check speedKmph").isEqualTo(expected.getSpeedKmph()))
            .satisfies(a -> assertThat(a.getBatteryPct()).as("check batteryPct").isEqualTo(expected.getBatteryPct()))
            .satisfies(a -> assertThat(a.getRecordedAt()).as("check recordedAt").isEqualTo(expected.getRecordedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalLocationLogUpdatableRelationshipsEquals(
        ProfessionalLocationLog expected,
        ProfessionalLocationLog actual
    ) {
        // empty method
    }
}
