package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalIncentiveAwardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalIncentiveAwardAllPropertiesEquals(
        ProfessionalIncentiveAward expected,
        ProfessionalIncentiveAward actual
    ) {
        assertProfessionalIncentiveAwardAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalIncentiveAwardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalIncentiveAwardAllUpdatablePropertiesEquals(
        ProfessionalIncentiveAward expected,
        ProfessionalIncentiveAward actual
    ) {
        assertProfessionalIncentiveAwardUpdatableFieldsEquals(expected, actual);
        assertProfessionalIncentiveAwardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalIncentiveAwardAutoGeneratedPropertiesEquals(
        ProfessionalIncentiveAward expected,
        ProfessionalIncentiveAward actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalIncentiveAward auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalIncentiveAwardUpdatableFieldsEquals(
        ProfessionalIncentiveAward expected,
        ProfessionalIncentiveAward actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalIncentiveAward relevant properties")
            .satisfies(a -> assertThat(a.getPeriodStart()).as("check periodStart").isEqualTo(expected.getPeriodStart()))
            .satisfies(a -> assertThat(a.getPeriodEnd()).as("check periodEnd").isEqualTo(expected.getPeriodEnd()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalIncentiveAwardUpdatableRelationshipsEquals(
        ProfessionalIncentiveAward expected,
        ProfessionalIncentiveAward actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalIncentiveAward relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getRule()).as("check rule").isEqualTo(expected.getRule()))
            .satisfies(a -> assertThat(a.getWalletTransaction()).as("check walletTransaction").isEqualTo(expected.getWalletTransaction()));
    }
}
