package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAllPropertiesEquals(Professional expected, Professional actual) {
        assertProfessionalAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAllUpdatablePropertiesEquals(Professional expected, Professional actual) {
        assertProfessionalUpdatableFieldsEquals(expected, actual);
        assertProfessionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAutoGeneratedPropertiesEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalUpdatableFieldsEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional relevant properties")
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getPhotoUrl()).as("check photoUrl").isEqualTo(expected.getPhotoUrl()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getOnboardingStatus()).as("check onboardingStatus").isEqualTo(expected.getOnboardingStatus()))
            .satisfies(a -> assertThat(a.getOnline()).as("check online").isEqualTo(expected.getOnline()))
            .satisfies(a -> assertThat(a.getAvgRating()).as("check avgRating").isEqualTo(expected.getAvgRating()))
            .satisfies(a -> assertThat(a.getJobsCompleted()).as("check jobsCompleted").isEqualTo(expected.getJobsCompleted()))
            .satisfies(a -> assertThat(a.getCancellationRate()).as("check cancellationRate").isEqualTo(expected.getCancellationRate()))
            .satisfies(a -> assertThat(a.getLastLat()).as("check lastLat").isEqualTo(expected.getLastLat()))
            .satisfies(a -> assertThat(a.getLastLng()).as("check lastLng").isEqualTo(expected.getLastLng()))
            .satisfies(a -> assertThat(a.getLastLocationAt()).as("check lastLocationAt").isEqualTo(expected.getLastLocationAt()))
            .satisfies(a -> assertThat(a.getJoinedAt()).as("check joinedAt").isEqualTo(expected.getJoinedAt()))
            .satisfies(a ->
                assertThat(a.getCashInHand())
                    .as("check cashInHand")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCashInHand())
            )
            .satisfies(a ->
                assertThat(a.getCashLimit()).as("check cashLimit").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCashLimit())
            )
            .satisfies(a -> assertThat(a.getMaxDailyJobs()).as("check maxDailyJobs").isEqualTo(expected.getMaxDailyJobs()))
            .satisfies(a -> assertThat(a.getLanguages()).as("check languages").isEqualTo(expected.getLanguages()))
            .satisfies(a -> assertThat(a.getBankAccountEnc()).as("check bankAccountEnc").isEqualTo(expected.getBankAccountEnc()))
            .satisfies(a -> assertThat(a.getIfscCode()).as("check ifscCode").isEqualTo(expected.getIfscCode()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalUpdatableRelationshipsEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional relationships")
            .satisfies(a -> assertThat(a.getHomeCity()).as("check homeCity").isEqualTo(expected.getHomeCity()))
            .satisfies(a -> assertThat(a.getTier()).as("check tier").isEqualTo(expected.getTier()))
            .satisfies(a -> assertThat(a.getZones()).as("check zones").isEqualTo(expected.getZones()));
    }
}
