package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalKycDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalKycDocumentAllPropertiesEquals(ProfessionalKycDocument expected, ProfessionalKycDocument actual) {
        assertProfessionalKycDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalKycDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalKycDocumentAllUpdatablePropertiesEquals(
        ProfessionalKycDocument expected,
        ProfessionalKycDocument actual
    ) {
        assertProfessionalKycDocumentUpdatableFieldsEquals(expected, actual);
        assertProfessionalKycDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalKycDocumentAutoGeneratedPropertiesEquals(
        ProfessionalKycDocument expected,
        ProfessionalKycDocument actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalKycDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalKycDocumentUpdatableFieldsEquals(
        ProfessionalKycDocument expected,
        ProfessionalKycDocument actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalKycDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocType()).as("check docType").isEqualTo(expected.getDocType()))
            .satisfies(a -> assertThat(a.getDocNumberEnc()).as("check docNumberEnc").isEqualTo(expected.getDocNumberEnc()))
            .satisfies(a -> assertThat(a.getFileUrl()).as("check fileUrl").isEqualTo(expected.getFileUrl()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getReviewedAt()).as("check reviewedAt").isEqualTo(expected.getReviewedAt()))
            .satisfies(a -> assertThat(a.getRejectReason()).as("check rejectReason").isEqualTo(expected.getRejectReason()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalKycDocumentUpdatableRelationshipsEquals(
        ProfessionalKycDocument expected,
        ProfessionalKycDocument actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalKycDocument relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
