package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalTimeOffAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTimeOffAllPropertiesEquals(ProfessionalTimeOff expected, ProfessionalTimeOff actual) {
        assertProfessionalTimeOffAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalTimeOffAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTimeOffAllUpdatablePropertiesEquals(ProfessionalTimeOff expected, ProfessionalTimeOff actual) {
        assertProfessionalTimeOffUpdatableFieldsEquals(expected, actual);
        assertProfessionalTimeOffUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTimeOffAutoGeneratedPropertiesEquals(ProfessionalTimeOff expected, ProfessionalTimeOff actual) {
        assertThat(actual)
            .as("Verify ProfessionalTimeOff auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTimeOffUpdatableFieldsEquals(ProfessionalTimeOff expected, ProfessionalTimeOff actual) {
        assertThat(actual)
            .as("Verify ProfessionalTimeOff relevant properties")
            .satisfies(a -> assertThat(a.getStartsAt()).as("check startsAt").isEqualTo(expected.getStartsAt()))
            .satisfies(a -> assertThat(a.getEndsAt()).as("check endsAt").isEqualTo(expected.getEndsAt()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTimeOffUpdatableRelationshipsEquals(ProfessionalTimeOff expected, ProfessionalTimeOff actual) {
        assertThat(actual)
            .as("Verify ProfessionalTimeOff relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()))
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
