package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalTierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierAllPropertiesEquals(ProfessionalTier expected, ProfessionalTier actual) {
        assertProfessionalTierAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalTierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierAllUpdatablePropertiesEquals(ProfessionalTier expected, ProfessionalTier actual) {
        assertProfessionalTierUpdatableFieldsEquals(expected, actual);
        assertProfessionalTierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierAutoGeneratedPropertiesEquals(ProfessionalTier expected, ProfessionalTier actual) {
        assertThat(actual)
            .as("Verify ProfessionalTier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierUpdatableFieldsEquals(ProfessionalTier expected, ProfessionalTier actual) {
        assertThat(actual)
            .as("Verify ProfessionalTier relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMinRating()).as("check minRating").isEqualTo(expected.getMinRating()))
            .satisfies(a -> assertThat(a.getMinJobs()).as("check minJobs").isEqualTo(expected.getMinJobs()))
            .satisfies(a ->
                assertThat(a.getCommissionPercent())
                    .as("check commissionPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCommissionPercent())
            )
            .satisfies(a -> assertThat(a.getDispatchPriority()).as("check dispatchPriority").isEqualTo(expected.getDispatchPriority()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierUpdatableRelationshipsEquals(ProfessionalTier expected, ProfessionalTier actual) {
        // empty method
    }
}
