package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalWalletAllPropertiesEquals(ProfessionalWallet expected, ProfessionalWallet actual) {
        assertProfessionalWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalWalletAllUpdatablePropertiesEquals(ProfessionalWallet expected, ProfessionalWallet actual) {
        assertProfessionalWalletUpdatableFieldsEquals(expected, actual);
        assertProfessionalWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalWalletAutoGeneratedPropertiesEquals(ProfessionalWallet expected, ProfessionalWallet actual) {
        assertThat(actual)
            .as("Verify ProfessionalWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalWalletUpdatableFieldsEquals(ProfessionalWallet expected, ProfessionalWallet actual) {
        assertThat(actual)
            .as("Verify ProfessionalWallet relevant properties")
            .satisfies(a ->
                assertThat(a.getBalance()).as("check balance").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBalance())
            )
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalWalletUpdatableRelationshipsEquals(ProfessionalWallet expected, ProfessionalWallet actual) {
        assertThat(actual)
            .as("Verify ProfessionalWallet relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
