package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalTrainingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTrainingAllPropertiesEquals(ProfessionalTraining expected, ProfessionalTraining actual) {
        assertProfessionalTrainingAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalTrainingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTrainingAllUpdatablePropertiesEquals(ProfessionalTraining expected, ProfessionalTraining actual) {
        assertProfessionalTrainingUpdatableFieldsEquals(expected, actual);
        assertProfessionalTrainingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTrainingAutoGeneratedPropertiesEquals(ProfessionalTraining expected, ProfessionalTraining actual) {
        assertThat(actual)
            .as("Verify ProfessionalTraining auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTrainingUpdatableFieldsEquals(ProfessionalTraining expected, ProfessionalTraining actual) {
        assertThat(actual)
            .as("Verify ProfessionalTraining relevant properties")
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTrainingUpdatableRelationshipsEquals(ProfessionalTraining expected, ProfessionalTraining actual) {
        assertThat(actual)
            .as("Verify ProfessionalTraining relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()));
    }
}
