package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalSkillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalSkillAllPropertiesEquals(ProfessionalSkill expected, ProfessionalSkill actual) {
        assertProfessionalSkillAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalSkillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalSkillAllUpdatablePropertiesEquals(ProfessionalSkill expected, ProfessionalSkill actual) {
        assertProfessionalSkillUpdatableFieldsEquals(expected, actual);
        assertProfessionalSkillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalSkillAutoGeneratedPropertiesEquals(ProfessionalSkill expected, ProfessionalSkill actual) {
        assertThat(actual)
            .as("Verify ProfessionalSkill auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalSkillUpdatableFieldsEquals(ProfessionalSkill expected, ProfessionalSkill actual) {
        assertThat(actual)
            .as("Verify ProfessionalSkill relevant properties")
            .satisfies(a -> assertThat(a.getSkillLevel()).as("check skillLevel").isEqualTo(expected.getSkillLevel()))
            .satisfies(a -> assertThat(a.getCertifiedAt()).as("check certifiedAt").isEqualTo(expected.getCertifiedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalSkillUpdatableRelationshipsEquals(ProfessionalSkill expected, ProfessionalSkill actual) {
        assertThat(actual)
            .as("Verify ProfessionalSkill relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
