package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalAvailabilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAvailabilityAllPropertiesEquals(
        ProfessionalAvailability expected,
        ProfessionalAvailability actual
    ) {
        assertProfessionalAvailabilityAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalAvailabilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAvailabilityAllUpdatablePropertiesEquals(
        ProfessionalAvailability expected,
        ProfessionalAvailability actual
    ) {
        assertProfessionalAvailabilityUpdatableFieldsEquals(expected, actual);
        assertProfessionalAvailabilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAvailabilityAutoGeneratedPropertiesEquals(
        ProfessionalAvailability expected,
        ProfessionalAvailability actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalAvailability auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAvailabilityUpdatableFieldsEquals(
        ProfessionalAvailability expected,
        ProfessionalAvailability actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalAvailability relevant properties")
            .satisfies(a -> assertThat(a.getDayOfWeek()).as("check dayOfWeek").isEqualTo(expected.getDayOfWeek()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAvailabilityUpdatableRelationshipsEquals(
        ProfessionalAvailability expected,
        ProfessionalAvailability actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalAvailability relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
