package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalTierHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierHistoryAllPropertiesEquals(ProfessionalTierHistory expected, ProfessionalTierHistory actual) {
        assertProfessionalTierHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalTierHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierHistoryAllUpdatablePropertiesEquals(
        ProfessionalTierHistory expected,
        ProfessionalTierHistory actual
    ) {
        assertProfessionalTierHistoryUpdatableFieldsEquals(expected, actual);
        assertProfessionalTierHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierHistoryAutoGeneratedPropertiesEquals(
        ProfessionalTierHistory expected,
        ProfessionalTierHistory actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalTierHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierHistoryUpdatableFieldsEquals(
        ProfessionalTierHistory expected,
        ProfessionalTierHistory actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalTierHistory relevant properties")
            .satisfies(a -> assertThat(a.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(expected.getEffectiveFrom()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalTierHistoryUpdatableRelationshipsEquals(
        ProfessionalTierHistory expected,
        ProfessionalTierHistory actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalTierHistory relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getTier()).as("check tier").isEqualTo(expected.getTier()));
    }
}
