package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalDailyMetricsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalDailyMetricsAllPropertiesEquals(
        ProfessionalDailyMetrics expected,
        ProfessionalDailyMetrics actual
    ) {
        assertProfessionalDailyMetricsAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalDailyMetricsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalDailyMetricsAllUpdatablePropertiesEquals(
        ProfessionalDailyMetrics expected,
        ProfessionalDailyMetrics actual
    ) {
        assertProfessionalDailyMetricsUpdatableFieldsEquals(expected, actual);
        assertProfessionalDailyMetricsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalDailyMetricsAutoGeneratedPropertiesEquals(
        ProfessionalDailyMetrics expected,
        ProfessionalDailyMetrics actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalDailyMetrics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalDailyMetricsUpdatableFieldsEquals(
        ProfessionalDailyMetrics expected,
        ProfessionalDailyMetrics actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalDailyMetrics relevant properties")
            .satisfies(a -> assertThat(a.getMetricDate()).as("check metricDate").isEqualTo(expected.getMetricDate()))
            .satisfies(a -> assertThat(a.getJobsOffered()).as("check jobsOffered").isEqualTo(expected.getJobsOffered()))
            .satisfies(a -> assertThat(a.getJobsAccepted()).as("check jobsAccepted").isEqualTo(expected.getJobsAccepted()))
            .satisfies(a -> assertThat(a.getJobsCompleted()).as("check jobsCompleted").isEqualTo(expected.getJobsCompleted()))
            .satisfies(a -> assertThat(a.getJobsCancelled()).as("check jobsCancelled").isEqualTo(expected.getJobsCancelled()))
            .satisfies(a -> assertThat(a.getOnlineMinutes()).as("check onlineMinutes").isEqualTo(expected.getOnlineMinutes()))
            .satisfies(a ->
                assertThat(a.getEarnings()).as("check earnings").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getEarnings())
            )
            .satisfies(a -> assertThat(a.getAvgRating()).as("check avgRating").isEqualTo(expected.getAvgRating()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalDailyMetricsUpdatableRelationshipsEquals(
        ProfessionalDailyMetrics expected,
        ProfessionalDailyMetrics actual
    ) {
        assertThat(actual)
            .as("Verify ProfessionalDailyMetrics relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
