package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ReferralRewardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralRewardAllPropertiesEquals(ReferralReward expected, ReferralReward actual) {
        assertReferralRewardAutoGeneratedPropertiesEquals(expected, actual);
        assertReferralRewardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralRewardAllUpdatablePropertiesEquals(ReferralReward expected, ReferralReward actual) {
        assertReferralRewardUpdatableFieldsEquals(expected, actual);
        assertReferralRewardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralRewardAutoGeneratedPropertiesEquals(ReferralReward expected, ReferralReward actual) {
        assertThat(actual)
            .as("Verify ReferralReward auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralRewardUpdatableFieldsEquals(ReferralReward expected, ReferralReward actual) {
        assertThat(actual)
            .as("Verify ReferralReward relevant properties")
            .satisfies(a ->
                assertThat(a.getRewardAmount())
                    .as("check rewardAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRewardAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralRewardUpdatableRelationshipsEquals(ReferralReward expected, ReferralReward actual) {
        assertThat(actual)
            .as("Verify ReferralReward relationships")
            .satisfies(a -> assertThat(a.getTriggerBooking()).as("check triggerBooking").isEqualTo(expected.getTriggerBooking()));
    }
}
