package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchKeywordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchKeywordAllPropertiesEquals(SearchKeyword expected, SearchKeyword actual) {
        assertSearchKeywordAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchKeywordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchKeywordAllUpdatablePropertiesEquals(SearchKeyword expected, SearchKeyword actual) {
        assertSearchKeywordUpdatableFieldsEquals(expected, actual);
        assertSearchKeywordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchKeywordAutoGeneratedPropertiesEquals(SearchKeyword expected, SearchKeyword actual) {
        assertThat(actual)
            .as("Verify SearchKeyword auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchKeywordUpdatableFieldsEquals(SearchKeyword expected, SearchKeyword actual) {
        assertThat(actual)
            .as("Verify SearchKeyword relevant properties")
            .satisfies(a -> assertThat(a.getKeyword()).as("check keyword").isEqualTo(expected.getKeyword()))
            .satisfies(a -> assertThat(a.getWeight()).as("check weight").isEqualTo(expected.getWeight()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchKeywordUpdatableRelationshipsEquals(SearchKeyword expected, SearchKeyword actual) {
        assertThat(actual)
            .as("Verify SearchKeyword relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
