package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceZoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceZoneAllPropertiesEquals(ServiceZone expected, ServiceZone actual) {
        assertServiceZoneAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceZoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceZoneAllUpdatablePropertiesEquals(ServiceZone expected, ServiceZone actual) {
        assertServiceZoneUpdatableFieldsEquals(expected, actual);
        assertServiceZoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceZoneAutoGeneratedPropertiesEquals(ServiceZone expected, ServiceZone actual) {
        assertThat(actual)
            .as("Verify ServiceZone auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceZoneUpdatableFieldsEquals(ServiceZone expected, ServiceZone actual) {
        assertThat(actual)
            .as("Verify ServiceZone relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPincode()).as("check pincode").isEqualTo(expected.getPincode()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceZoneUpdatableRelationshipsEquals(ServiceZone expected, ServiceZone actual) {
        assertThat(actual)
            .as("Verify ServiceZone relationships")
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getProfessionals()).as("check professionals").isEqualTo(expected.getProfessionals()));
    }
}
