package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceTranslationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceTranslationAllPropertiesEquals(ServiceTranslation expected, ServiceTranslation actual) {
        assertServiceTranslationAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceTranslationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceTranslationAllUpdatablePropertiesEquals(ServiceTranslation expected, ServiceTranslation actual) {
        assertServiceTranslationUpdatableFieldsEquals(expected, actual);
        assertServiceTranslationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceTranslationAutoGeneratedPropertiesEquals(ServiceTranslation expected, ServiceTranslation actual) {
        assertThat(actual)
            .as("Verify ServiceTranslation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceTranslationUpdatableFieldsEquals(ServiceTranslation expected, ServiceTranslation actual) {
        assertThat(actual)
            .as("Verify ServiceTranslation relevant properties")
            .satisfies(a -> assertThat(a.getLangKey()).as("check langKey").isEqualTo(expected.getLangKey()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceTranslationUpdatableRelationshipsEquals(ServiceTranslation expected, ServiceTranslation actual) {
        assertThat(actual)
            .as("Verify ServiceTranslation relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
