package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServicePackageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePackageAllPropertiesEquals(ServicePackage expected, ServicePackage actual) {
        assertServicePackageAutoGeneratedPropertiesEquals(expected, actual);
        assertServicePackageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePackageAllUpdatablePropertiesEquals(ServicePackage expected, ServicePackage actual) {
        assertServicePackageUpdatableFieldsEquals(expected, actual);
        assertServicePackageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePackageAutoGeneratedPropertiesEquals(ServicePackage expected, ServicePackage actual) {
        assertThat(actual)
            .as("Verify ServicePackage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePackageUpdatableFieldsEquals(ServicePackage expected, ServicePackage actual) {
        assertThat(actual)
            .as("Verify ServicePackage relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getBasePrice()).as("check basePrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBasePrice())
            )
            .satisfies(a -> assertThat(a.getMrp()).as("check mrp").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMrp()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePackageUpdatableRelationshipsEquals(ServicePackage expected, ServicePackage actual) {
        assertThat(actual)
            .as("Verify ServicePackage relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
