package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServiceAddonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAddonAllPropertiesEquals(ServiceAddon expected, ServiceAddon actual) {
        assertServiceAddonAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceAddonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAddonAllUpdatablePropertiesEquals(ServiceAddon expected, ServiceAddon actual) {
        assertServiceAddonUpdatableFieldsEquals(expected, actual);
        assertServiceAddonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAddonAutoGeneratedPropertiesEquals(ServiceAddon expected, ServiceAddon actual) {
        assertThat(actual)
            .as("Verify ServiceAddon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAddonUpdatableFieldsEquals(ServiceAddon expected, ServiceAddon actual) {
        assertThat(actual)
            .as("Verify ServiceAddon relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAddonUpdatableRelationshipsEquals(ServiceAddon expected, ServiceAddon actual) {
        assertThat(actual)
            .as("Verify ServiceAddon relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
