package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SlotCapacityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotCapacityAllPropertiesEquals(SlotCapacity expected, SlotCapacity actual) {
        assertSlotCapacityAutoGeneratedPropertiesEquals(expected, actual);
        assertSlotCapacityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotCapacityAllUpdatablePropertiesEquals(SlotCapacity expected, SlotCapacity actual) {
        assertSlotCapacityUpdatableFieldsEquals(expected, actual);
        assertSlotCapacityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotCapacityAutoGeneratedPropertiesEquals(SlotCapacity expected, SlotCapacity actual) {
        assertThat(actual)
            .as("Verify SlotCapacity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotCapacityUpdatableFieldsEquals(SlotCapacity expected, SlotCapacity actual) {
        assertThat(actual)
            .as("Verify SlotCapacity relevant properties")
            .satisfies(a -> assertThat(a.getSlotStart()).as("check slotStart").isEqualTo(expected.getSlotStart()))
            .satisfies(a -> assertThat(a.getSlotEnd()).as("check slotEnd").isEqualTo(expected.getSlotEnd()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getBookedCount()).as("check bookedCount").isEqualTo(expected.getBookedCount()))
            .satisfies(a -> assertThat(a.getBlocked()).as("check blocked").isEqualTo(expected.getBlocked()))
            .satisfies(a ->
                assertThat(a.getPriceMultiplier())
                    .as("check priceMultiplier")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPriceMultiplier())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotCapacityUpdatableRelationshipsEquals(SlotCapacity expected, SlotCapacity actual) {
        assertThat(actual)
            .as("Verify SlotCapacity relationships")
            .satisfies(a -> assertThat(a.getZone()).as("check zone").isEqualTo(expected.getZone()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
