package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SlotHoldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotHoldAllPropertiesEquals(SlotHold expected, SlotHold actual) {
        assertSlotHoldAutoGeneratedPropertiesEquals(expected, actual);
        assertSlotHoldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotHoldAllUpdatablePropertiesEquals(SlotHold expected, SlotHold actual) {
        assertSlotHoldUpdatableFieldsEquals(expected, actual);
        assertSlotHoldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotHoldAutoGeneratedPropertiesEquals(SlotHold expected, SlotHold actual) {
        assertThat(actual)
            .as("Verify SlotHold auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotHoldUpdatableFieldsEquals(SlotHold expected, SlotHold actual) {
        assertThat(actual)
            .as("Verify SlotHold relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSlotHoldUpdatableRelationshipsEquals(SlotHold expected, SlotHold actual) {
        assertThat(actual)
            .as("Verify SlotHold relationships")
            .satisfies(a -> assertThat(a.getSlotCapacity()).as("check slotCapacity").isEqualTo(expected.getSlotCapacity()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
