package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SosAlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSosAlertAllPropertiesEquals(SosAlert expected, SosAlert actual) {
        assertSosAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertSosAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSosAlertAllUpdatablePropertiesEquals(SosAlert expected, SosAlert actual) {
        assertSosAlertUpdatableFieldsEquals(expected, actual);
        assertSosAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSosAlertAutoGeneratedPropertiesEquals(SosAlert expected, SosAlert actual) {
        assertThat(actual)
            .as("Verify SosAlert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSosAlertUpdatableFieldsEquals(SosAlert expected, SosAlert actual) {
        assertThat(actual)
            .as("Verify SosAlert relevant properties")
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSosAlertUpdatableRelationshipsEquals(SosAlert expected, SosAlert actual) {
        assertThat(actual)
            .as("Verify SosAlert relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
