package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupportTicketAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportTicketAllPropertiesEquals(SupportTicket expected, SupportTicket actual) {
        assertSupportTicketAutoGeneratedPropertiesEquals(expected, actual);
        assertSupportTicketAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportTicketAllUpdatablePropertiesEquals(SupportTicket expected, SupportTicket actual) {
        assertSupportTicketUpdatableFieldsEquals(expected, actual);
        assertSupportTicketUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportTicketAutoGeneratedPropertiesEquals(SupportTicket expected, SupportTicket actual) {
        assertThat(actual)
            .as("Verify SupportTicket auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportTicketUpdatableFieldsEquals(SupportTicket expected, SupportTicket actual) {
        assertThat(actual)
            .as("Verify SupportTicket relevant properties")
            .satisfies(a -> assertThat(a.getTicketNo()).as("check ticketNo").isEqualTo(expected.getTicketNo()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupportTicketUpdatableRelationshipsEquals(SupportTicket expected, SupportTicket actual) {
        assertThat(actual)
            .as("Verify SupportTicket relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
