package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TrainingModuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingModuleAllPropertiesEquals(TrainingModule expected, TrainingModule actual) {
        assertTrainingModuleAutoGeneratedPropertiesEquals(expected, actual);
        assertTrainingModuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingModuleAllUpdatablePropertiesEquals(TrainingModule expected, TrainingModule actual) {
        assertTrainingModuleUpdatableFieldsEquals(expected, actual);
        assertTrainingModuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingModuleAutoGeneratedPropertiesEquals(TrainingModule expected, TrainingModule actual) {
        assertThat(actual)
            .as("Verify TrainingModule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingModuleUpdatableFieldsEquals(TrainingModule expected, TrainingModule actual) {
        assertThat(actual)
            .as("Verify TrainingModule relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContentUrl()).as("check contentUrl").isEqualTo(expected.getContentUrl()))
            .satisfies(a -> assertThat(a.getMandatory()).as("check mandatory").isEqualTo(expected.getMandatory()))
            .satisfies(a -> assertThat(a.getPassScore()).as("check passScore").isEqualTo(expected.getPassScore()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrainingModuleUpdatableRelationshipsEquals(TrainingModule expected, TrainingModule actual) {
        assertThat(actual)
            .as("Verify TrainingModule relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
