package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserMembershipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMembershipAllPropertiesEquals(UserMembership expected, UserMembership actual) {
        assertUserMembershipAutoGeneratedPropertiesEquals(expected, actual);
        assertUserMembershipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMembershipAllUpdatablePropertiesEquals(UserMembership expected, UserMembership actual) {
        assertUserMembershipUpdatableFieldsEquals(expected, actual);
        assertUserMembershipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMembershipAutoGeneratedPropertiesEquals(UserMembership expected, UserMembership actual) {
        assertThat(actual)
            .as("Verify UserMembership auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMembershipUpdatableFieldsEquals(UserMembership expected, UserMembership actual) {
        assertThat(actual)
            .as("Verify UserMembership relevant properties")
            .satisfies(a -> assertThat(a.getStartsAt()).as("check startsAt").isEqualTo(expected.getStartsAt()))
            .satisfies(a -> assertThat(a.getEndsAt()).as("check endsAt").isEqualTo(expected.getEndsAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMembershipUpdatableRelationshipsEquals(UserMembership expected, UserMembership actual) {
        assertThat(actual)
            .as("Verify UserMembership relationships")
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()));
    }
}
