package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserConsentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserConsentAllPropertiesEquals(UserConsent expected, UserConsent actual) {
        assertUserConsentAutoGeneratedPropertiesEquals(expected, actual);
        assertUserConsentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserConsentAllUpdatablePropertiesEquals(UserConsent expected, UserConsent actual) {
        assertUserConsentUpdatableFieldsEquals(expected, actual);
        assertUserConsentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserConsentAutoGeneratedPropertiesEquals(UserConsent expected, UserConsent actual) {
        assertThat(actual)
            .as("Verify UserConsent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserConsentUpdatableFieldsEquals(UserConsent expected, UserConsent actual) {
        assertThat(actual)
            .as("Verify UserConsent relevant properties")
            .satisfies(a -> assertThat(a.getPurpose()).as("check purpose").isEqualTo(expected.getPurpose()))
            .satisfies(a -> assertThat(a.getPolicyVersion()).as("check policyVersion").isEqualTo(expected.getPolicyVersion()))
            .satisfies(a -> assertThat(a.getGranted()).as("check granted").isEqualTo(expected.getGranted()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserConsentUpdatableRelationshipsEquals(UserConsent expected, UserConsent actual) {
        // empty method
    }
}
