package com.limitcross.facility.domain;

import static com.limitcross.facility.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class WalletTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAllPropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertWalletTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertWalletTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAllUpdatablePropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertWalletTransactionUpdatableFieldsEquals(expected, actual);
        assertWalletTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionAutoGeneratedPropertiesEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(actual)
            .as("Verify WalletTransaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionUpdatableFieldsEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(actual)
            .as("Verify WalletTransaction relevant properties")
            .satisfies(a -> assertThat(a.getTxnType()).as("check txnType").isEqualTo(expected.getTxnType()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a ->
                assertThat(a.getBalanceAfter())
                    .as("check balanceAfter")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBalanceAfter())
            )
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWalletTransactionUpdatableRelationshipsEquals(WalletTransaction expected, WalletTransaction actual) {
        assertThat(actual)
            .as("Verify WalletTransaction relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()))
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
