package com.limitcross.facility.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WarrantyClaimAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyClaimAllPropertiesEquals(WarrantyClaim expected, WarrantyClaim actual) {
        assertWarrantyClaimAutoGeneratedPropertiesEquals(expected, actual);
        assertWarrantyClaimAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyClaimAllUpdatablePropertiesEquals(WarrantyClaim expected, WarrantyClaim actual) {
        assertWarrantyClaimUpdatableFieldsEquals(expected, actual);
        assertWarrantyClaimUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyClaimAutoGeneratedPropertiesEquals(WarrantyClaim expected, WarrantyClaim actual) {
        assertThat(actual)
            .as("Verify WarrantyClaim auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyClaimUpdatableFieldsEquals(WarrantyClaim expected, WarrantyClaim actual) {
        assertThat(actual)
            .as("Verify WarrantyClaim relevant properties")
            .satisfies(a -> assertThat(a.getIssue()).as("check issue").isEqualTo(expected.getIssue()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getWithinWarranty()).as("check withinWarranty").isEqualTo(expected.getWithinWarranty()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarrantyClaimUpdatableRelationshipsEquals(WarrantyClaim expected, WarrantyClaim actual) {
        assertThat(actual)
            .as("Verify WarrantyClaim relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()))
            .satisfies(a -> assertThat(a.getRedoBooking()).as("check redoBooking").isEqualTo(expected.getRedoBooking()));
    }
}
